replicaCount: 1

image:
  repository: openworklabs/lotus:ntwk-calibration-8.8.0
  pullPolicy: IfNotPresent #Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: acc

podSecurityContext:
  fsGroup: 2000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: false
  runAsUser: 1000

service:
  type: ClusterIP
  port: 1234
  targetPort: 1234

ingress:
  enabled: true
  host: dev.node.glif.io
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Length,Content-Range,Range"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecDebugLog /tmp/modsec_debug.log
    # nginx.ingress.kubernetes.io/server-alias: "_"
  lotus:
    enabled: true
    annotations: 
    #  nginx.ingress.kubernetes.io/configuration-snippet: |
    #    proxy_set_header Authorization "Bearer <JWT>";
    #  nginx.ingress.kubernetes.io/whitelist-source-range: "91.149.128.236/32"
  ipfs:
    enabled: true
  powergate:
    enabled: true

init:
  sync:
    enabled: true
  import:
    enabled: false
    # ideally a shared volume containing chain dump
    volume: {}
      #- name: filecoin-chain-vol
      #  persistentVolumeClaim:
      #    claimName: efs-claim

secretVolume:
  enabled: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#  lotus:
#    requests:
#      cpu: 1000m
#      memory: 4Gi
#    limits:
#      cpu: 3000m
#      memory: 12Gi
#  ipfs:
#    requests:
#      cpu: 2000m
#      memory: 2Gi
#    limits:
#      cpu: 3000m
#      memory: 4Gi
#  powergate:
#    requests:
#      cpu: 1000m
#      memory: 2Gi
#    limits:
#      cpu: 2000m
#      memory: 3Gi

persistence:
  enabled: true
  snapshots:
    uploadToIpfs: 
      enabled: true
    enabled: true
    automation:
      deletion: 
        enabled: true
        retention:
          count: 2
      creation: 
        enabled: true
    restore: 
      enabled: false
      #name: snapshotname
  lotus:
    size: "50Gi"
    accessModes:
      - ReadWriteOnce
  ipfs:
    size: "50Gi"
    accessModes:
      - ReadWriteOnce
  powergate:
    size: "50Gi"
    accessModes:
      - ReadWriteOnce

Powergate:
  enabled: true

IPFS:
  enabled: true
  
nodeSelector: {}

tolerations: []

affinity: {}
