persistence:
   enabled: false

nodeSelector:
  enabled: true
ingress:
  lotus:
    enabled: false
  statediff:
    enabled: true

Lotus:
  enabled: false
  service:
    enabled: false
StateDiff:
  enabled: true

lotusDNS: api-read-lotus-service

persistence:
  enabled: false
  snapshots:
    automation:
      deletion:
        enabled: false
      creation:
        enabled: false
