persistence:
   enabled: false

nodeSelector:
  enabled: true
  nodeLabel:
    lifecycle: Ec2Spot
# powergate, ipfs in api-service mode don't work now. don't enable it.
ingress:
  lotus:
    enabled: false
  statediff:
    enabled: true

Lotus:
  enabled: false
StateDiff:
  enabled: true

lotusDNS: api-read-lotus-service

persistence:
  snapshots:
    automation:
      deletion:
        enabled: false
      creation:
        enabled: false
