{{- if .Values.ingress.lotus.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-lotus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
{{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.ingress.lotus.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
{{- if .Values.cache.enabled }}
              serviceName: {{ .Release.Name }}-cache-service
              servicePort: 8080
            path: /cache(/|$)(.*)
{{- else }}
              serviceName: {{ .Release.Name }}-lotus-service
              servicePort: 1234
            path: /{{ .Release.Name }}/lotus(/|$)(.*)
{{- end }}
{{- end }}
