{{- if .Values.Powergate.enabled }}
{{- if .Values.ingress.powergate.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-powergate
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$3
{{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.ingress.powergate.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:    
      paths:
        - backend:
            serviceName: {{ .Release.Name }}-powergate-service
            servicePort: 5002
          path: /{{ .Release.Name }}/powergate/(grpc|5002)(/|$)(.*)
        - backend:
            serviceName: {{ .Release.Name }}-powergate-service
            servicePort: 6002
          path: /{{ .Release.Name }}/powergate/(webproxy|6002)(/|$)(.*)
        - backend:
            serviceName: {{ .Release.Name }}-powergate-service
            servicePort: 6060
          path: /{{ .Release.Name }}/powergate/(6060)(/|$)(.*)
        - backend:
            serviceName: {{ .Release.Name }}-powergate-service
            servicePort: 7000
          path: /{{ .Release.Name }}/powergate/(web|7000)(/|$)(.*)
        - backend:
            serviceName: {{ .Release.Name }}-powergate-service
            servicePort: 8889
          path: /{{ .Release.Name }}/powergate/(8889)(/|$)(.*)          
{{- end }}
{{- end }}
