{{- if .Values.persistence.efs }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-efs-lotus-{{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.lotus.size | quote }}
  volumeMode: Filesystem
  accessModes:
    {{- range .Values.persistence.lotus.accessModes }}
    - {{ . | quote }}
    {{- end }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.lotus.storageClassName }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.persistence.efs }}
{{- end }}
