{{- if .Values.cache.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cache-service
  labels:
    app: lotus-cache
spec:
  selector:
    app: lotus-cache
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cache-deployment
spec:
  selector:
    matchLabels:
      app: lotus-cache
  replicas: 1
  template:
    metadata:
      labels:
        app: lotus-cache
    spec:
      containers:
        - name: lotus-cache
          image: {{ .Values.cache.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 8Gi
              cpu: 2
            requests:
              memory: 2Gi
              cpu: 500m
      nodeSelector:
        lifecycle: Ec2Spot-i3
{{- end }}
