{{- if .Values.cache.enabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-cache-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Length,Content-Range,Range"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    # nginx.ingress.kubernetes.io/server-alias: "_"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecDebugLog /tmp/modsec_debug.log
spec:
  rules:
    - host: dev.node.glif.io
      http:
        paths:
          - backend:
              serviceName: lotus-cache-service
              servicePort: 8080
            path: /cache(/|$)(.*)

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cache-service
  labels:
    app: lotus-cache
spec:
  selector:
    app: lotus-cache
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cache-deployment
spec:
  selector:
    matchLabels:
      app: lotus-cache
  replicas: 1
  template:
    metadata:
      labels:
        app: lotus-cache
    spec:
      containers:
        - name: lotus-cache
          image: {{ .Values.cache.container.image }}
          imagePullPolicy: Always
#          env:
#          - name: proxy_url
#            value: {{ .Values.cache.container.proxyurl }}
#          - name: jwt_secret_base64
#            value: {{ .Values.cache.container.jwtsecret }}
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 8Gi
              cpu: 2
            requests:
              memory: 2Gi
              cpu: 500m
      nodeSelector:
        lifecycle: Ec2Spot-i3
{{- end }}
