{{- if or .Values.serviceAccount.create .Values.persistence.snapshots.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-{{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "chart.labels" . | nindent 4 }}
{{- end }}

{{- if .Values.persistence.snapshots.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}-role 
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots"]
  verbs: ["list", "describe", "patch", "replace", "get", "delete", "create"] 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-{{ .Values.serviceAccount.name }} 
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Chart.Name }}-role 
  apiGroup: rbac.authorization.k8s.io
{{- end }}
